name: buscoannotation_getbuscogene
description: Get genes from BUSCO output.
keywords:
  - busco
  - tsv
  - csv
tools:
  - "buscoannotation":
      description: a tool kit to extract ancestral gene based on the busco result
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - tsv:
      type: file
      description: Output full table TSV file from BUSCO process
      pattern: "*.tsv"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - csv:
      type: file
      description: CSV file containing extracted genes
      pattern: "*.csv"
authors:
  - "@weaglesBio"
