name: arima_2readsbamcombiner

description: Combin two paired single read bam files into one sorted bam
keywords:
  - samtools
  - combine
  - sort
  - arima
tools:
  - arima:
      description: Combin paired subgke read bam files into one sorted bam using Samtools and Perl script
      homepage: https://arimagenomics.com/
      documentation: https://usermanual.wiki/Document/ArimaMappingUserGuideA160156v01.424413804/view
      tool_dev_url: https://github.com/ArimaGenomics/mapping_pipeline/blob/master/two_read_bam_combiner.pl

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bams:
      type: file
      description: Paired single read BAM files
      pattern: "*.bam"
  - qscore:
      type: value
      description: Minimum map quality filter

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bam:
      type: file
      description: Sorted combined BAM file
      pattern: "*.bam"

authors:
  - "@gq1"
