name: fastk_fastk
description: constructing fastk database from high quality reads
keywords:
  - fastk
tools:
  - fastk_fastk:
      description: k‑mer counter that is optimized for processing high quality DNA assembly data sets
      homepage: https://github.com/thegenemyers/FASTK/blob/master/README.md
      documentation: https://github.com/thegenemyers/FASTK/blob/master/README.md
      tool_dev_url: https://github.com/thegenemyers/FASTK
      doi: ""
      licence: Copyright (c) 2020, Dr. Eugene W. Myers (EWM). All rights reserved.

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - trimmedReads:
      type: file
      description: compressed fasta file
      pattern: "*.fasta.gz"

  - kmer:
    type: value
    description: the size/length of kmer

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]

  - hist:
      type: file
      description: fastk kmer database
      pattern: "*.hist"

  - ktab:
      type: file
      description: A sorted table of all canonical k‑mers along with their counts.
      pattern: "*.ktab"

  - prof:
      type: file
      description: A k‑mer count profile of each sequence in the input data set.
      pattern: "*.prof"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@yumisims"
