name: "selfcomp_mummer2bed"
description: module to convert standard 4 columns output to bed file format and filtered by given motif length
keywords:
  - mummer2bed
tools:
  - "selfcomp":
      description: |
        module to convert standard 4 columns output to bed file format and filtered by given motif length.
        output bed file is in tab separated format
        reference_id ref_start ref_end query_id matching_length forward/reverse  query_start query_end sizeof_query

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - mummerfile:
      type: file
      description: mummerfile file
      pattern: "*.*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bedfile:
      type: file
      description: bed file output of mummer2bed
      pattern: "*.bed"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@yumisims"
