name: miniprot_align
description: A versatile pairwise aligner for genomic and spliced nucleotide sequences
keywords:
  - align
  - fasta
  - protein
  - genome
  - paf
  - gff
tools:
  - miniprot:
      description: |
        A versatile pairwise aligner for genomic and protein sequences.
      homepage: https://github.com/lh3/miniprot
      documentation: https://github.com/lh3/miniprot
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - pep:
      type: file
      description: a fasta file contains one or multiple protein sequences
  - ref:
      type: file
      description: Reference database in FASTA format.
  - paf_format:
      type: boolean
      description: Specify that output CIGAR should be in PAF format
  - gff_format:
      type: boolean
      description: Specify that output should be in gff3 format
  - gtf_format:
      type: boolean
      description: Specify that output should be in gtf format
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - paf:
      type: file
      description: Alignment in PAF format
      pattern: "*.paf"
  - gff:
      type: file
      description: Alignment in gff format
      pattern: "*.gff"
  - gtf:
      type: file
      description: Alignment in gtf format
      pattern: "*.gtf"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@yumisims"
