name: "selfcomp_mapids"
description: Script to map ids in .bed file using .agp file.
keywords:
  - map
  - bed
  - agp
tools:
  - "selfcomp":
      licence: "sanger"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: BED file
      pattern: "*.{bed}"
  - agp:
      type: file
      description: AGP file
      pattern: "*.{agp}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bed:
      type: file
      description: Mapped BED file
      pattern: "*.{bed}"
authors:
  - "@weaglesBio"