name: "buscoannotation_buscopainterlep"
description: Paints chromosomes of lepidopteran genomes with BUSCOs. Script developed by Charlotte Wright.
keywords:
  - busco
  - tsv
  - lepidoptera
tools:
  - "buscoannotation":
      description: a tool kit to extract ancestral gene based on the busco result
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - full_table_tsv:
      type: file
      description: Output full table TSV file from BUSCO process
      pattern: "*.tsv"
  - merian_tsv:
      type: file
      description: TSV of reference file of merian ancestral units. Compiled by Charlotte Wright
      pattern: "*.tsv"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - complete_location_tsv:
      type: file
      description: TSV file containing location and status of all shared complete BUSCOs.
      pattern: "*_complete_location.tsv"
  - duplicated_location_tsv:
      type: file
      description: TSV file containing location and status of all duplicated BUSCOs.
      pattern: "*_duplicated_location.tsv"
  - summary_tsv:
      type: file
      description: TSV file containing a summary of the chromosomal assignments.
      pattern: "*_summary.tsv"
authors:
  - "@weaglesBio"
